### PR TITLE
Zoning Appeals, vuejs and carto update.

### PR DESCRIPTION
**Pull request by alejandroxlopez**
Hi Tim, 

This is the new version of Zoning Appeals, we have the green light from Andrew N. to deploy this update. 
The Vuejs application for production is in the "dist" folder.

The same folder is already running on https://cityofphiladelphia.github.io/zoning-appeals-stage/ if you want to take a look before the merge and deploy on this official repository.

Any questions let me know,

Thank you very much.

### CODE REVIEW

**Comment by alejandroxlopez** [comment]
Logo and breadcrumbs issue fixed.

**Comment by alejandroxlopez** [comment]
Now fixed the scroll behavior when you are on the bottom of the first page and do click on any of the items of the table, now, instead of going to the bottom on the next page, it stays on top like a standard page redirect.

**Comment by alejandroxlopez** [comment]
I did a last update to setup dist/ to work correctly on http://cityofphiladelphia.github.io/zoning-appeals/

**Comment by timwis** [comment]
Once you merge to `master`, it won't deploy automatically. Technically you could do what the current `README.md` says and create an orphan branch inside the `dist` directory and deploy it manually, but probably the easiest thing to do would be to wire it up with Travis-CI, similar to how we've done it for [carto-api-explorer](https://github.com/CityOfPhiladelphia/carto-api-explorer/blob/master/.travis.yml).

First, remove the `dist` folder from source control by adding it to `.gitignore` and using `git rm -rf dist`. This directory isn't "source code," it's compiled/built code that gets deployed, so we'll have our CI tool actually do the building and deploy the result to `gh-pages` instead.

Second, add `.travis.yml` to the root directory with these contents:

```yaml
language: node_js
node_js:
  - "6"
script:
  - npm run build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
```

Third, in the [travis ci dashboard](https://travis-ci.org/), enable travis for this repository.

Fourth, in order for it to deploy to this repo, you'll need to give it a github token as an environment variable in the settings panel of travis-ci. To get a github token, go to your [personal access tokens](https://github.com/settings/tokens) and create a new one. Make sure when you add it to travis, "display value in build log" is _off_.

Once that's done, you should be able to merge this pull request to master and watch it deploy! Make sure you have enough time to troubleshoot. I'm around to help on slack.

**Pull request merged**
